name: android

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Setup Flutter
        uses: subosito/flutter-action@main
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build boilerplate code
        run: ./gen.sh
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
      - name: Build apk
        run: ./build.sh apk --flavor dev
      - name: Upload a build artifact
        uses: actions/upload-artifact@main
        with:
          path:
            build/app/outputs/.*.apk
